server:
  port: 8082
  servlet:
    context-path: /Shopme
spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
    #hikari:
      #minimum-idle: 1
      #maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 871879069021-hcquuocpc6dptrg45gs3deoi2b56dbsv.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 3609992219233688
            client-secret: f979a29b1b376eb80c60cfefdfcb405e
            scope:
            - email
            - public_profile